services:
  postgres:
    image: postgres:16
    container_name: piyi-postgres
    environment:
      POSTGRES_DB: piyi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - piyi_postgres_data:/var/lib/postgresql/data

volumes:
  piyi_postgres_data:
